#pragma once

/* enable/disable LEDs based on layout */
#undef RGB_BACKLIGHT_USE_SPLIT_BACKSPACE
#define RGB_BACKLIGHT_USE_SPLIT_BACKSPACE 1
#undef RGB_BACKLIGHT_USE_SPLIT_LEFT_SHIFT
#define RGB_BACKLIGHT_USE_SPLIT_LEFT_SHIFT 1
#undef RGB_BACKLIGHT_USE_SPLIT_RIGHT_SHIFT
#define RGB_BACKLIGHT_USE_SPLIT_RIGHT_SHIFT 1
#undef RGB_BACKLIGHT_USE_7U_SPACEBAR
#define RGB_BACKLIGHT_USE_7U_SPACEBAR 0
#undef RGB_BACKLIGHT_USE_ISO_ENTER
#define RGB_BACKLIGHT_USE_ISO_ENTER 1
#undef RGB_BACKLIGHT_DISABLE_HHKB_BLOCKER_LEDS
#define RGB_BACKLIGHT_DISABLE_HHKB_BLOCKER_LEDS 0

#undef VENDOR_ID
#define VENDOR_ID       0x046D
#undef PRODUCT_ID
#define PRODUCT_ID      0xC31C
#undef DEVICE_VER
#define DEVICE_VER      0x0064
#undef MANUFACTURER
#define MANUFACTURER    Logitech
#undef PRODUCT
#define PRODUCT         USB Keyboard
#undef DESCRIPTION
#define DESCRIPTION     K120 Keyboard

#define PREVENT_STUCK_MODIFIERS
